// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GRABBER_H
#define GRABBER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Grabber: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	bool upright_out = false;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Solenoid* purpleTopLights;
	Solenoid* greenTopLight;
	Solenoid* toteGripper;
	DoubleSolenoid* pusher;
	Solenoid* containerUpright;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Grabber();
	void InitDefaultCommand();

	void grab(bool grab);
	void grab();
	void ungrab();
	void push(bool push);
	void push();
	void unpush();
	void topLights(bool light);
	void upright(bool upright);
	void upright();
	void uprightOut();
	void uprightToggle();
};

#endif
